config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#delete'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: :user_id
  has_many :attendees, :through => :event_attendees, foreign_key: :event_id
  has_many :event_attendees

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date <= ?', Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  # Event reference
  belongs_to :attended_event, class_name: "Event", foreign_key: :event_id

  # User reference
  belongs_to :attendee, class_name: "User", foreign_key: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :token
  before_create :remember 
  has_many :events
  has_many :event_attendees
  has_many :attended_events, :through => :event_attendees, foreign_key: :user_id

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.token = User.new_token
    self.remember_token = Digest::SHA1.hexdigest(token)
  end

  def authenticated?(given_token)
    BCrypt::Password.new(remember_token).is_password?(given_token)
  end

  def upcoming_events
    self.attended_events.where("date >= ?", Date.today)
  end

  def previous_events
    self.attended_events.where("date <= ?", Date.today)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      current_user=(user)
    else 
      @current_user = nil
    end
  end

  def current_user=(user)
    if user && user.authenticated?(cookies[:remember_token])
      log_in user
      @current_user = user 
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else
      render 'new'
    end
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  # @upcoming_events = current_user.upcoming_events

  private
    def event_params
      params.require(:event).permit(:location, :description, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      remember user
      redirect_to user
    else 
      flash.now[:danger] = 'Invalid email/password combo'
      render 'new'
    end
  end

  def delete
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end    
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all 
  end
  
  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<% provide(:title, 'Events') %>

<div id="upcoming_event_container">
  <h1>Upcoming Events:</h1>
  <% if !Event.upcoming.nil? %>
    <% Event.upcoming.each do |e| %>
      <h3><ul class="list-inline center-block text-center">
        <li><%= link_to e.location, event_path(e) %></li>
      </ul></h3>
    <% end %>
  <% end %>
</div>

<div id="past_event_container">
  <h1>Previous Events:</h1>
  <% if !Event.past.nil? %>
    <% Event.past.each do |e| %>
      <h3><ul class="list-inline center-block text-center">
        <li><%= link_to e.location, event_path(e) %></li>
      </ul></h3>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<%= provide(tite: 'New Event') %>
  <h1>Create event</h1>

<%= form_for @event do |f| %>
  
  <p>
  <%= f.label :location %>
  <%= f.text_field :location %>
  </p>

  <p>
  <%= f.label :date %>
  <%= f.date_field :date %>
  </p>

  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </p>

  <p><%= f.submit 'Create event' %>

<% end %>

app/views/events/show.html.erb
<%= provide(:title, @event.location) %>

<%= "Created by #{@event.creator.name}" %>

<div id="event_details_container">
  <h1><%= @event.location %></h1>
  <h2>Event Attendees:</h2>
    <% @event.attendees.each do |t| %>
    <h3><ul class="list-inline center-block text-center">
      <li><%= link_to t.name, user_path(t) %></li>
    </ul></h3>
    <% end %>
</div> 

app/views/layouts/_header.html.erb
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "All Events", events_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="<%= 'active' if current_page?(user_path(current_user)) %>"><%= link_to "My Events", user_path(current_user) %></li>
          <li class="<%= 'active' if current_page?(new_event_path) %>"><%= link_to "Create Event", new_event_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign Up',new_user_path %></li>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to Private Events</h1>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<%= form_for @user do |f| %> 
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <p><%= f.submit 'Create' %></p>
  
<% end %>

<p><%= link_to "Already registered? Log in now", login_path %></p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div id="created_events_container">
  <h1>
    <%= @user == current_user ? "My events:" : "Events #{@user.name} has created:" %>
  </h1>
  <% if !@user.events.nil? %>  
    <% @user.events.each do |e| %>
      <h3><ul class= "list-inline center-block text-center">
        <li><%= link_to e.location, event_path(e) %></li>
      </ul></h3>
    <% end %>
  <% end %>
</div>

<div id="upcoming_events_container">
  <h1>
    <%= @user == current_user ? "Upcoming events I'm attending:" : "Upcoming events #{@user.name} is attending:" %>
  </h1>
  <% if !@user.upcoming_events.empty? %>
    <% @user.upcoming_events.each do |e| %>
      <h3><ul class="list-inline center-block text-center">
        <li><%= link_to e.location, event_path(e) %></li>
      </ul></h3>
    <% end %>
  <% end %>
</div>

<div id="past_events_container">
  <h1>
    <%= @user == current_user ? "Past events I've attended:" : "Past events #{@user.name} has attended:" %>
  </h1>
  <% if !@user.previous_events.empty? %>
    <% @user.previous_events.each do |e| %>
      <h3><ul class="list-inline center-block text-center">
        <li><%= link_to e.location, event_path(e) %></li>
      </ul></h3>
    <% end %>
  <% end %>
</div>